#!/bin/bash

# HOW TO RUN THIS PROJECT - Simple Demo Script
# This script demonstrates the complete setup and run process

echo "=========================================="
echo "   AI Agent Using CrewAI - Demo Guide"
echo "=========================================="
echo ""
echo "This project is now fully configured and ready to run!"
echo ""
echo "📋 Here's what has been set up for you:"
echo ""
echo "✅ Setup script (setup.sh) - Installs dependencies automatically"
echo "✅ Run script (run.sh) - Easy menu to run the project"
echo "✅ Environment template (.env.example) - Template for API keys"
echo "✅ Error handling - Helpful messages if something goes wrong"
echo "✅ Documentation - README.md, QUICKSTART.md, and TESTING.md"
echo ""
echo "=========================================="
echo "   Quick Start - Just 3 Steps!"
echo "=========================================="
echo ""
echo "Step 1: Run the setup"
echo "  $ ./setup.sh"
echo ""
echo "Step 2: Add your API keys to .env file"
echo "  $ nano .env"
echo "  (Get keys from: https://platform.openai.com/api-keys"
echo "                   https://serper.dev/api-key)"
echo ""
echo "Step 3: Run the project"
echo "  $ ./run.sh"
echo ""
echo "=========================================="
echo "   Alternative: Manual Commands"
echo "=========================================="
echo ""
echo "If you prefer manual control:"
echo ""
echo "# Activate virtual environment"
echo "$ source venv/bin/activate"
echo ""
echo "# Run main script (automated AI healthcare research)"
echo "$ python main.py"
echo ""
echo "# OR run research agent (interactive, choose your topic)"
echo "$ python research_agents.py"
echo ""
echo "=========================================="
echo "   What Each Script Does"
echo "=========================================="
echo ""
echo "main.py:"
echo "  - Researches AI in healthcare automatically"
echo "  - Uses Senior Researcher + Writer agents"
echo "  - Saves blog post to new-blog-post.md"
echo ""
echo "research_agents.py:"
echo "  - Interactive research on any topic you choose"
echo "  - Prompts you for a research topic"
echo "  - Displays results in the terminal"
echo ""
echo "=========================================="
echo "   Documentation Available"
echo "=========================================="
echo ""
echo "📖 README.md      - Full documentation with troubleshooting"
echo "⚡ QUICKSTART.md  - Fast 3-step guide to get started"
echo "🧪 TESTING.md     - Testing results and verification"
echo ""
echo "=========================================="
echo ""
echo "🎉 The project is ready! Follow the steps above to run it."
echo ""
